name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Web Linter and Formatting check
        run: pnpm --filter web run check

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          cd apps/api
          poetry install

      - name: Run Python Ruff Checks
        run: |
          cd apps/api
          poetry run ruff check .

      - name: Run Python Ruff Formatting check
        run: |
          cd apps/api
          poetry run ruff format --check .

      - name: Run Python Mypy Type checking
        run: |
          cd apps/api
          poetry run mypy .
